language: objective-c
osx_image: xcode611
before_install:
  - gem install xcpretty
script:  
- xcodebuild -workspace Example/FormManager.xcworkspace -scheme FormManager-Example -sdk iphonesimulator8.1 | xcpretty -c
- pod lib lint --quick