language: objective-c
osx_image: xcode7.2
before_install:
  - gem install xcpretty
script:  
- xcodebuild -workspace Example/FormManager.xcworkspace -scheme FormManager-Example -sdk iphonesimulator9.1 | xcpretty -c
- pod lib lint --quick